baseURL = "https://chciples.cz"
languageCode = "cs"
title = "Chciples.cz"

[params]
    siteURL = "https://chciples.cz"
    lang = "cs"
    locale = "cs_CZ"
    gatag = "UA-53675598-6"
[params.seo]
    image = "/images/og-image.jpg"

[menu]
    [[menu.main]]
        url = "/"
        name = "Organizace plesů"
        weight = 1
    [[menu.main]]
        url = "/#zaridime"
        name = "Co zařídíme"
        weight = 2
    #[[menu.main]]
    #    url = "/zkusenosti/"
    #    name = "Zkušenosti"
    [[menu.main]]
        url = "/kontakt/"
        name = "Kontakt"
        weight = 3
